### PR TITLE
migrate to cucumber 4.0.0

### PR DESCRIPTION
**Pull request by cliviu**

### CODE REVIEW

**Comment by GianniGiglio** [comment]
Hi what is the status for this pull request. looking forward for that one :)

**Comment by wakaleo** [comment]
Still work-in-progress: Cucumber 4 is not backward compatible with Cucumber 2 and will break existing test suites, so there needs to be the possibility of working with both, which is difficult because the APIs have totally changed.

**Comment by faragm** [comment]
Is there any expected date to release?

**Comment by mleegwt** [comment]
According to https://docs.cucumber.io/cucumber/step-definitions/#expressions the expressions as regexp should still be possible (but I have not tested that statement). Are there any other incompatibilities? If so, I guess it would help to have a list so we can work towards a solution together.

**Comment by wakaleo** [comment]
Deployed in serenity-cucumber4

**Pull request closed without merging**
