### PR TITLE
Fix serenity report generation when run by multiple tags

### PR DESCRIPTION
**Pull request by rraghuna**
Before this change when cucumber features or scenarios are run based on logical ORs and ANDs of two or more tags, serenity fails to create tests report. This change would fix this issue and as a result when a user runs cucumber with tags as mentioned in this link (https://github.com/cucumber/cucumber/wiki/Tags) serenity report with tests on it would be generated.

The tests are added to the maven project in the path: serenity-cucumber\src\smoketests. The feature file name is serenity_report_when_using_tags_at_all_leve.feature and Junit test name is WhenUsingScenarioOutlineAndTagsAtAllLevels.java.

### CODE REVIEW

**Comment by wakaleo** [comment]
Thanks for this. 
  - The code in examplesMatchFilter() is now quite complex, could you extract the logic and add some unit tests to document how it works?
  - There are also some binary files (in the `out` directory) that have slipped into the commit.

**Comment by rraghuna** [comment]
Hi @wakaleo 

Sorry I could not understand your comments quite well. Before I work on the suggested changes, I would like to clarify the below:

1) _The code in examplesMatchFilter() is now quite complex, could you extract the logic_ - What I understand is that you want me to create a layer of abstraction by logically putting away the blocks of code from examplesMatchFilter() into new methods. Please correct me If I my understanding is wrong.

2) Regarding binary files - This is my reason to do a "git rm --cached <classfilename>" on them. When I cloned the forked repo into my local, these class files automatically moved to unstaged area of git. I tried to replace those class files in the worktree to the files in the index by doing "git checkout -- <classFilename> on them. But soon after they moved again automatically to the unstaged area (I did not compile code or run tests). I thought these class files need not be tracked in git anyway (please correct me if I am wrong), so I did "git rm --cached <classfilename>" and added the folder in the .gitignore file. I work on having them back then I will end up with the same problem described here. Please advise.

**Comment by rraghuna** [comment]
Hi @wakaleo 

I have added the unit and integration tests and have refactored the examplesMatchFilter().  To ensure a cleaner commit history, I have created another pull request #115 containing these updates. I hope you are fine with the class files being untracked, if not please suggest what to do with the issue I am facing with the class files. Thanks, Ram.

**Comment by rraghuna** [comment]
Closing this pull request as it is no longer required

**Pull request closed without merging**
